### LOGS USER INTO THE SYSTEM BY EMAIL AND PASSWORD
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "12345678"
}


### LOGS OUT CURRENT LOGGED-IN USER SESSION
POST {{host}}/api/auth/logout
Authorization: Bearer {{accessToken}}
Content-Type: application/json

### FORGOT PASSWORD
POST {{host}}/api/auth/forgot-password
Content-Type: application/json

{
  "email": "{{email}}"
}

### RESET PASSWORD
POST {{host}}/api/auth/reset-password
Content-Type: application/json

{
  "token": "{{passwordToken}}",
  "password": "{{newPassword}}"
}

### REFRESH TOKEN
POST {{host}}/api/auth/refresh-token
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

### LOGS USER INTO THE SYSTEM THROUGH A FACEBOOK
POST {{host}}/api/auth/platform
Content-Type: application/json

{
  "token": "{{facebookToken}}",
  "platform": "facebook"
}

### LOGS USER INTO THE SYSTEM THROUGH A APPLE
POST {{host}}/api/auth/platform
Content-Type: application/json

{
  "token": "{{appleToken}}",
  "platform": "apple"
}

### LOGS USER INTO THE SYSTEM THROUGH A GITHUB
POST {{host}}/api/auth/platform
Content-Type: application/json

{
  "token": "{{githubToken}}",
  "platform": "github"
}
