### LOGIN [USER]
# @name loginUser
POST {{apiUrl}}/v1/auth/login

{
  "email": "{{$dotenv REST_USER_LOGIN}}",
  "password": "{{$dotenv REST_USER_PASSWORD}}"
}

### LOGOUT [USER]
POST {{apiUrl}}/v1/auth/logout
Authorization: Bearer {{loginUser.response.body.data.payload.accessToken}}

### LOGOUT [USER]
POST {{apiUrl}}/v1/auth/logout
Cookie: accessToken={{loginUser.response.body.data.payload.accessToken}}

### REFRESH-TOKEN [USER]
POST {{apiUrl}}/v1/auth/refresh-token

{
  "refreshToken": "{{loginUser.response.body.data.payload.refreshToken}}"
}

### LOGS USER INTO THE SYSTEM THROUGH A APPLE
POST {{apiUrl}}/v1/auth/platform

{
  "token": "{{$dotenv REST_APPLE_TOKEN}}",
  "platform": "apple"
}

### LOGS USER INTO THE SYSTEM THROUGH A FACEBOOK
POST {{apiUrl}}/v1/auth/platform

{
  "token": "{{$dotenv REST_FACEBOOK_TOKEN}}",
  "platform": "facebook"
}


### LOGS USER INTO THE SYSTEM THROUGH A GOOGLE
POST {{apiUrl}}/v1/auth/platform

{
  "token": "{{$dotenv REST_GOOGLE_TOKEN}}",
  "platform": "github"
}

### LOGS USER INTO THE SYSTEM THROUGH A GITHUB
POST {{apiUrl}}/v1/auth/platform

{
  "token": "{{$dotenv REST_GITHUB_TOKEN}}",
  "platform": "github"
}

### FORGOT PASSWORD BY EMAIL
POST {{apiUrl}}/v1/auth/password/email

{
  "email": "{{$dotenv REST_USER_LOGIN}}",
}
