### GET CURRENT USER
GET {{baseUrl}}/api/users/current
Authorization: Bearer {{$dotenv HTTP_ACCESS_TOKEN}}

### UPDATE CURRENT USER
PUT {{baseUrl}}/api/users/current
Authorization: Bearer {{$dotenv HTTP_ACCESS_TOKEN}}

{
  "email": "test@test.test",
  "profile": {
    "firstName": "Dmitry",
    "lastName": "Neverovski"
  }
}

### CREATE USER
POST {{baseUrl}}/api/users

{
  "email": "test@test.test",
  "password": "123456",
  "profile": {
    "firstName": "D.",
    "lastName": "N."
  }
}
