### GET CURRENT USER
GET {{host}}/api/users/current
Authorization: Bearer {{accessToken}}
Content-Type: application/json

### UPDATE CURRENT USER
PUT {{host}}/api/users/current
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "profile": {
    "firstName": "Dmitry",
    "lastName": "Neverovski"
  }
}

### CREATE USER
POST {{host}}/api/users
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}",
  "profile": {
    "firstName": "D.",
    "lastName": "N."
  }
}

### RESET PASSWORD
POST {{host}}/api/users/reset-password
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "oldPassword": "{{password}}",
  "newPassword": "{{newPassword}}"
}
