export const NOTIFICATION_QUEUE = 'NOTIFICATION_QUEUE';

export const NOTIFICATION_REGISTRATION = 'NOTIFICATION_REGISTRATION';
export const NOTIFICATION_PASSWORD_RESET = 'NOTIFICATION_PASSWORD_RESET';
export const NOTIFICATION_VERIFICATION = 'NOTIFICATION_VERIFICATION';
export const NOTIFICATION_PASSWORD_CHANGED = 'NOTIFICATION_PASSWORD_CHANGED';
